language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pushd /tmp
  - wget https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
  - unzip protoc-3.7.1-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
  - cd ./WUProtos_Base
  - chmod +x ./compile.py
  - ./compile.py python -o ../ --keep_proto_files
  - cd ..
  - chmod 755 -R ./wuprotos
  - cd ./various_scripts
  - chmod +x ./clean.py
  - ./clean.py
  - chmod +x ./gdc_split.py
  - ./gdc_split.py
  - cd ..
  - chmod +x ./gamefiles_decode.py
  - ./gamefiles_decode.py
  - chmod +x ./extract_objects.py
  - ./extract_objects.py
