language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - cd ./WUProtos_Base
  - chmod +x ./compile.py
  - ./compile.py python -o ../ --keep_proto_files
  - cd ..
  - chmod +x ./*.py
  - ./gamefiles_decode.py
